export const ActionTypes = {
    SET_TIME_SHEET_DATA: "SET_TIME_SHEET_DATA",
    SET_TIME_SHEET_ALL_DATA: "SET_TIME_SHEET_ALL_DATA",
    SET_USERS_DATA: "SET_USERS_DATA",
    SET_USERLOGIN: "SET_USERLOGIN",
    SET_WORK_DAY_HOURS: "SET_WORK_DAY_HOURS"
};