export const ActionTypes = {
    SET_ADD_SICK_LEAVE_DATA: 'SET_ADD_SICK_LEAVE_DATA',
    SET_DELETE_ADD_SICK_LEAVE_DATA: 'SET_DELETE_ADD_SICK_LEAVE_DATA',
    SET_RESET_ADD_SICK_LEAVE_DATA: 'SET_RESET_ADD_SICK_LEAVE_DATA',
};