export const localization = {
  SIGN_IN_BTN: "SIGN IN",
  CHANGE_PASSWORD_BTN: "SUBMIT",
  LOGIN: "LOGIN",
  PASSWORD: "PASSWORD",
  TIME: "TIME",
  TIME_SMALL: "Time",
  TIME_EDIT: "TimeEdit",
  EDIT_TIME: "Edit Time",
  EDIT_TIME_ALL: "Edit Time All",
  TIMESHEET: "TIMESHEET",
  PROFILE: "PROFILE",
  EDIT_PROFILE: "Edit Profile",
  CHANGE_PASSWORD: "Change Password",
  LOG_OUT: "Log Out",
  DELETE: "DELETE",
  DELETE_SMALL: "Delete",
  EDIT_SMALL: "Edit",
  SEND: "SEND",
  SEND_SMALL: "Send",
  ADD: "ADD NEW",
  DESCRIPTION: "Description",
  SELECT_DATA: "Select data",
  REASON_OF_APPEAL: "Reason of appeal",
  DATE: "Date",
  IN: "In",
  OUT: "Out",
  TOTAL: "Total",
  DIFFERENCE: "Difference",
  UNKNOWN: "Unknown",
  CHANGE: "Change",
  ADD_TIME: "Add time",
  ADD_VACATION: "Add vacation",
  ADD_SICK_LEAVE: "Add sick leave",
  ADD_ALL_DATA: "Add all data",
  GENERATE_TIMESHEET: "Generate timesheet",
  TIMESHEETS_STATUSES: "Timesheets statuses",
  SICK_LEAVE: "Sick leave",
  VACATION: "Vacation",
  NOTIFICATIONS: "Notifications",
  TIMESHEET_LIST: "Timesheet List",
  TIME_LOG: "APPROVE TIME",
  APPROVE_TIME: "Approve time",
  TIME_LOG_LIST: "Time list",
  APPROVE: "APPROVE",
  APPROVE_SMALL: "Approve",
  DECLINE: "DECLINE",
  DECLINA_SMALL: "Decline",
  SELECT_DATE: "Select date: ",
  SELECTED_DATE: "Selected date:  ",
  SELECTED_TIME: "Selected time:  ",
  SELECTED_REASON: "Reason of appeal:  ",
  SELECTED_DESCRIPTION: "Description:  ",
  THERE_IS_NO_FINGERPRINTS_YET: "THERE IS NO FINGERPRINTS YET",
  SELECT_USER: "Select user",
  CUD_REASON: "Cud reason",
  CREATOR: "Creator",
  CREATED_TIME: "Created time",
  ADDED_BY: "Added by",
  CREATE_TIME: "Create time",
  STATUS: "Status",
  MONTH_YEAR: "Month/Year",
  UPDATE_TIME: "Update time",
  CREATED_DAY: "Created day",
  CREATED_BY: "Created by",
  TOTAL_HOURS: "Total hours",
  TOTAL_WORK_DAYS: "Total work days",
  SICK_DAYS: "Sick days",
  VACATION_DAYS: "Vacation days",
  PENDING: "Pending",
  APPROVED: "Approved",
  NO_DATA: "No data",
  DATE_TIME_HISTORY: "Date/Time: ",
  ADDED_BY_HISTORY: "Added by: ",
  DESCRIPTION_HISTORY: "Description: ",
  REASON_HISTORY: "Reason: ",
  HISTORY: "HISTORY",
  EMPTY: "Empty",
  APPROVING_PROCESS_HISTORY: "Approving process",
  TOTAL_WORKDAYS: "Total workdays",
  HOLIDAYS: "Holidays",
  SHORT_DAYS: "Short days",
  VACATION: "Vacation",
  SICK_LEAVE_DAYS: "Sick leave days",
  TOTAL_WEEKENDS: "Weekends",
  ACTUAL_WORKDAYS: "Actual workdays",
  TARGET_HOURS: "Target hours",
  TOTAL_HOURS: "Total hours",
  TOTAL_TIME_DIFFERENCE: "Total time difference"
};