export const ActionTypes = {
    SET_DELETE_TIME_DATA: 'SET_DELETE_TIME_DATA',
    SET_SEND_TIME_DATA: 'SET_SEND_TIME_DATA',
    SET_SEND_VACATION_SICK_LEAVE_DATA: "SET_SEND_VACATION_SICK_LEAVE_DATA",
};