export const ActionTypes = {
    SET_SELECT_USER_LIST: 'SET_SELECT_USER_LIST',
    SET_USER_LIST: 'SET_USER_LIST',
    SET_USER_PROFILE: 'SET_USER_PROFILE',
    SET_SELECTED_USER_ID: 'SET_SELECTED_USER_ID',
};