export const ActionTypes = {
    SET_TIMESHEET_LIST: "SET_TIMESHEET_LIST",
    SET_TIMESHEET_ALL_LIST: "SET_TIMESHEET_ALL_LIST",
    SET_APPROVE_TIMESHEET: "SET_APPROVE_TIMESHEET",
    SET_EXPORT_TIMESHEET: "SET_EXPORT_TIMESHEET"
};