export const ActionTypes = {
    SET_APPROVE_TIME_LIST: 'SET_APPROVE_TIME_LIST',
    SET_IS_LOADING_APPROVE_TIME: 'SET_IS_LOADING_APPROVE_TIME',
    SET_APPROVE_DATE: 'SET_APPROVE_DATE',
    SET_TIME_FOR_DELETE: 'SET_TIME_FOR_DELETE',
    SET_IS_LOADING_DELETE_TIME: 'SET_IS_LOADING_DELETE_TIME',
    SET_FILTERS: 'SET_FILTERS',
    CLEAR_FILTERS: 'CLEAR_FILTERS',
};