export const ActionTypes = {
    SET_ADD_SHORT_HOLIDAY_TIME_DATA: 'SET_ADD_SHORT_HOLIDAY_TIME_DATA',
    SET_DELETE_ADD_SHORT_HOLIDAY_TIME_DATA: 'SET_DELETE_ADD_SHORT_HOLIDAY_TIME_DATA',
    SET_RESET_ADD_SHORT_HOLIDAY_TIME_DATA: 'SET_RESET_ADD_SHORT_HOLIDAY_TIME_DATA',
};