export const ActionTypes = {
    SET_ROLES_CMD: 'SET_ROLES_CMD',
    SET_INITIAL_DATA: 'SET_INITIAL_DATA',
    SET_IS_AUTHORIZED: 'SET_IS_AUTHORIZED',
    SET_USER_TOKEN_DATA: 'SET_USER_TOKEN_DATA',
    SET_PASSWORD: 'SET_PASSWORD'
};