export const ActionTypes = {
    SET_DATE: 'SET_DATE',
    SET_ROLES: 'SET_ROLES',
    SET_GENDERS: 'SET_GENDERS',
    SET_REASONS: 'SET_REASONS',
    SET_STATUSES: 'SET_STATUSES',
    SET_TIME_TYPE: 'SET_TIME_TYPE',
    SET_DEPARTMENTS: 'SET_DEPARTMENTS',
    SET_APPROVE_STATUSES: 'SET_APPROVE_STATUSES',
    SET_SNACKBAR: 'SET_SNACKBAR',
    SET_ACCLISTCONTROL: 'SET_ACCLISTCONTROL',
    SET_DATE_TYPE: 'SET_DATE_TYPE',
};