export const ActionTypes = {
    SET_GENERATE_TIMESHEET: "SET_GENERATE_TIMESHEET",
    SET_GENERATE_TIMESHEET_ALL: "SET_GENERATE_TIMESHEET_ALL",
    SET_GLOBAL_TIMESHEET: "SET_GLOBAL_TIMESHEET",
    SET_GENERATE_WEEKS: "SET_GENERATE_WEEKS"
};