export const ActionTypes = {
    SET_ADD_VACATION_DATA: 'SET_ADD_VACATION_DATA',
    SET_DELETE_ADD_VACATION_DATA: 'SET_DELETE_ADD_VACATION_DATA',
    SET_RESET_ADD_VACATION_DATA: 'SET_RESET_ADD_VACATION_DATA',
};