export const ActionTypes = {
    SET_WORKDAY_HOURS: 'SET_WORKDAY_HOURS',
    SET_VIETIME_ALL_DATA: "SET_VIETIME_ALL_DATA",
    SET_VACATION_DAYS: 'SET_VACATION_DAYS',
    SET_SICKLEAVE_DAYS: 'SET_SICKLEAVE_DAYS',
    SET_WORKDAYS: 'SET_WORKDAYS'
};